---
deployment:
  tasks:
    - /home/ficmacok/virtualenv/wms.ficma.co.ke/3.10/bin/pip install -r /home/ficmacok/wms/requirements.txt
    - /home/ficmacok/virtualenv/wms.ficma.co.ke/3.10/bin/python /home/ficmacok/wms/manage.py collectstatic --noinput
    - /home/ficmacok/virtualenv/wms.ficma.co.ke/3.10/bin/python /home/ficmacok/wms/manage.py migrate --noinput
    # You might need to restart the application for changes to take effect.
    # cPanel's git deployment might do this automatically, or you might need to add a touch tmp/restart.txt
    # or use a cPanel API call if available in this context.
    # For now, focus on getting it running manually.
