# Generated by Django 4.2.10 on 2025-04-28 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0003_branch_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to=settings.AUTH_USER_MODEL),
        ),
    ]
