# Generated by Django 5.2 on 2025-04-10 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=100)),
                ('dispatch_code', models.CharField(max_length=50, unique=True)),
                ('total_parcels', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Finalized'), (2, 'In Transit'), (3, 'Delivered'), (4, 'Cancelled')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waybill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_tracking_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sender', models.CharField(max_length=100)),
                ('sender_telephone', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=100)),
                ('receiver_telephone', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_methods', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Finalized'), (2, 'In Transit'), (3, 'Delivered'), (4, 'Cancelled')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='dispatch.dispatch')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.parcel')),
            ],
            options={
                'unique_together': {('dispatch', 'parcel')},
            },
        ),
    ]
