# Generated by Django 4.2.10 on 2025-04-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
