alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: wmsandroidapi
region: blr
features:
- buildpack-stack=ubuntu-22
services:
- name: wms-android-wms-android-api
  github:
    repo: dot-contracts/WMS_Android
    branch: aisino
    deploy_on_push: true
  dockerfile_path: Dockerfile
  source_dir: wms_android.api
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  envs:
    # API Settings
    - key: ASPNETCORE_ENVIRONMENT
      scope: RUN_AND_BUILD_TIME
      value: Production
    - key: ASPNETCORE_URLS
      scope: RUN_AND_BUILD_TIME
      value: http://+:8080
    - key: PORT
      scope: RUN_AND_BUILD_TIME
      value: "8080"

    # Database Configuration
    - key: DB_HOST
      scope: RUN_AND_BUILD_TIME
      value: 139.59.12.69
    - key: DB_PORT
      scope: RUN_AND_BUILD_TIME
      value: "5432"
    - key: DB_NAME
      scope: RUN_AND_BUILD_TIME
      value: ficma_wms
    - key: DB_USER
      scope: RUN_AND_BUILD_TIME
      value: wms_user
    - key: DB_PASSWORD
      scope: RUN_AND_BUILD_TIME
      type: SECRET
      value: 2019@_Ficma

    # JWT Configuration
    - key: JWT__Secret
      scope: RUN_AND_BUILD_TIME
      type: SECRET
      value: fylcgkjrPuKMDU84pKuHNazEJ2YPVEXbR7H9yjwOJJk=
    - key: JWT__ExpiryInDays
      scope: RUN_AND_BUILD_TIME
      value: "7"

    # Logging Configuration
    - key: Logging__LogLevel__Default
      scope: RUN_AND_BUILD_TIME
      value: Information
    - key: Logging__LogLevel__Microsoft
      scope: RUN_AND_BUILD_TIME
      value: Warning

    # CORS Settings
    - key: AllowedOrigins
      scope: RUN_AND_BUILD_TIME
      value: "*"
ingress:
  rules:
  - component:
      name: wms-android-wms-android-api
    match:
      path:
        prefix: /
